version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - web
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@assembly3d.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"

  app:
    build:
      context: ./viewer-app
      dockerfile: Dockerfile
    container_name: 3d-viewer
    restart: always
    networks:
      - web
    volumes:
      - /usr/src/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`www.assembly3d.ru`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app-http.rule=Host(`www.assembly3d.ru`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  web:
    external: false 