name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      working-directory: viewer-app
      run: bun install

    - name: Format code with Biome
      working-directory: viewer-app
      run: bun run format

    - name: Commit formatting changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code with Biome" && git push)

    - name: Lint with Biome
      working-directory: viewer-app
      run: bun run lint

    - name: Type check
      working-directory: viewer-app
      run: bun run tsc --noEmit

    - name: Build
      working-directory: viewer-app
      run: bun run build
